export const route = {
  START: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FEED: "/main/feed",
  BUSINESS: "/main/business",
  MYINFO: "/main/myinfo",
  NOTIFICATION: "/notification",
  PROFILE: "/profile",
  SEARCH: "/search",
  SETTING: "/setting",
  ARTICLE_WRITE: "/article",
  MESSAGE: "/message",
  MESSAGE_SEND: "/message/send",
  BUSINESS_LICENSE: "/business-license",
  MY_ARTICLE: "/my-article",
  MY_COMMENT: "/my-comment",
  MY_LIKED_ARTICLE: "/my-liked-article",
  BLOCKED_USERS: "/blocked-users",
  ARTICLE_DETAIL: (id: number) => `/article/${id}`,
  ARTICLE_COMMENT_REPLY: (id: number, commentId: number) =>
    `/article/${id}/comment/${commentId}/reply`,
  NOTICE: "/notice",
  NOTICE_DETAIL: (id: number | string) => `/notice/${id}`,
  FAQ: "/faq",
  FAQ_DETAIL: (id: number) => `/faq/${id}`,
  EDITORS: "/editors",
  EDITOR_DETAIL: (id: string) => `/editors/${id}`,
} as const;
